### PR TITLE
Add a serializer for `java.util.Locale`

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Review by Kantis — APPROVED** [review]
Nice 👍

**Comment by sschuberth** [comment]
@Kantis, could you also click the merge button? 😉

**Comment by sschuberth** [comment]
> @Kantis, could you also click the merge button? 😉

Ping again @Kantis 😀

**Comment by Kantis** [comment]
@sschuberth sorry for the delay and thanks for merging @aSemy 🙏🏼

**Pull request merged**
