### PR TITLE
Use Kotlin's built-in Base64 en-/decoding

### PR DESCRIPTION
**Pull request by sschuberth**
This requires to raise the Kotin API level to 1.8.

### CODE REVIEW

**Comment by sschuberth** [comment]
I'm not sure what needs to happen top the mention of base64 in `gradle/kotlin-js-store/yarn.lock`...

**Comment by sschuberth** [comment]
Also, should we now move the only remaining file `ByteArrayAsBase64StringSerializer.kt` out of the `base64` package, and remove that package?

**Comment by Kantis** [comment]
Yeah, sounds like the package is not really needed anymore 👍🏼

**Comment by sschuberth** [comment]
> Yeah, sounds like the package is not really needed anymore 👍🏼

I've added a commit for the move.

**Comment by sschuberth** [comment]
> I'm not sure what needs to happen to the occurrence of `base64id` in `gradle/kotlin-js-store/yarn.lock`... if anything.

Can you still comment on this one @Kantis? Does anything need to be done here?

**Comment by Kantis** [comment]
> > I'm not sure what needs to happen to the occurrence of `base64id` in `gradle/kotlin-js-store/yarn.lock`... if anything.
> 
> Can you still comment on this one @Kantis? Does anything need to be done here?

Sorry, missed that. Nothing to be done. It looks like a transitive dependency of Karma and is unrelated to our base64 serialization. (JS lib used by Kotlin/JS afaik)

**Review by Kantis — APPROVED** [review]

**Pull request merged**
